PlacementManagementSystem/force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PlacementManagementSystem/force-app/main/default/objects/Job__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

PlacementManagementSystem/force-app/main/default/objects/Job__c/fields/Graduation_Year_c__c.field-meta.xml
<CustomField>
    <fullName>Graduation_Year_c__c</fullName>
    <defaultValue>YEAR(TODAY())</defaultValue>
    <label>Graduation_Year__c</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PlacementManagementSystem/force-app/main/default/objects/Job__c/fields/Package_LPA__c.field-meta.xml
<CustomField>
    <fullName>Package_LPA__c</fullName>
    <label>Package (LPA)</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

PlacementManagementSystem/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PlacementManagementSystem/force-app/main/default/objects/Student__c/fields/Backlogs__c.field-meta.xml
<CustomField>
    <fullName>Backlogs__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Backlogs</label>
    <type>Checkbox</type>
</CustomField>

PlacementManagementSystem/force-app/main/default/objects/Student__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CSE</fullName>
            </value>
            <value>
                <fullName>ECE</fullName>
            </value>
            <value>
                <fullName>EEE</fullName>
            </value>
            <value>
                <fullName>MECH</fullName>
            </value>
            <value>
                <fullName>CIVIL</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PlacementManagementSystem/force-app/main/default/objects/Student__c/fields/Student_User__c.field-meta.xml
<CustomField>
    <fullName>Student_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

PlacementManagementSystem/force-app/main/default/classes/EligibleJobsService.cls
public with sharing class EligibleJobsService {

    // ==========================================================
    // GET ELIGIBLE JOBS FOR CURRENT STUDENT
    // ==========================================================

    public static List<Job__c> getEligibleJobs() {

        // ======================================================
        // CURRENT LOGGED-IN USER
        // ======================================================

        Id currentUserId = UserInfo.getUserId();


        // ======================================================
        // FIND STUDENT LINKED TO CURRENT USER
        // ======================================================

        List<Student__c> students = [

            SELECT Id,
                   CGPA__c,
                   Department__c,
                   Backlogs__c,
                   Graduation_Year_c__c

            FROM Student__c

            WHERE Student_User__c = :currentUserId

            LIMIT 1

        ];


        // ======================================================
        // NO STUDENT FOUND
        // ======================================================

        if (students.isEmpty()) {

            return new List<Job__c>();

        }


        Student__c student = students[0];


        // ======================================================
        // GET JOB RECORDS
        // ======================================================

        List<Job__c> jobs = [

            SELECT Id,
                   Name,
                   Company__c,
                   Company__r.Name,
                   Closing_Date__c,
                   Graduation_Year_c__c,
                   Job_Location__c,
                   Minimum_CGPA__c,
                   Package_LPA__c,
                   Status__c

            FROM Job__c

            WHERE Closing_Date__c >= :Date.today()

            ORDER BY CreatedDate DESC

        ];


        // ======================================================
        // STORE ELIGIBLE JOBS
        // ======================================================

        List<Job__c> eligibleJobs =
            new List<Job__c>();


        // ======================================================
        // CHECK EACH JOB
        // ======================================================

        for (Job__c job : jobs) {


            // ==================================================
            // CGPA CHECK
            // ==================================================

            if (
                student.CGPA__c == null ||
                job.Minimum_CGPA__c == null ||
                student.CGPA__c < job.Minimum_CGPA__c
            ) {

                continue;

            }


            // ==================================================
            // BACKLOG CHECK
            // ==================================================

            if (student.Backlogs__c == true) {

                continue;

            }


            // ==================================================
            // GRADUATION YEAR CHECK
            // ==================================================

            if (
                student.Graduation_Year_c__c == null ||
                job.Graduation_Year_c__c == null ||
                student.Graduation_Year_c__c != job.Graduation_Year_c__c
            ) {

                continue;

            }


            // ==================================================
            // JOB PASSED ELIGIBILITY CHECKS
            // ==================================================

            eligibleJobs.add(job);

        }


        // ======================================================
        // RETURN ELIGIBLE JOBS
        // ======================================================

        return eligibleJobs;

    }

}